### ISSUE TITLE
retorno do datepicker incompativel

### ISSUE THREAD

**Issue by a0th** [a0th/ubet#4]
O retorno do datepicker esta incompatível com a linguagem corrente.

**Comment by a0th** [comment]
https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Famsul%2Fpickadate.js%2Fblob%2F3.5.6%2Flib%2Ftranslations%2Fpt_BR.js&h=PAQHMO2IGAQEXgg1ll3qRsNqf2hYtWaVhd6VzwzTBcEpgsw

**Comment by felipevfa** [comment]
Tornou-se irrelevante, pois o datepicker foi substituído.
