### ISSUE TITLE
Ultima reuniao

### ISSUE THREAD

**Issue by a0th** [a0th/ubet#8]
- [x] 1.  help_text do username: avisar de antemao condicoes para cadastro do username
- [x] 2.  cor de erro do formulario confunde com cor de fundo
- [x] 3.  captcha HEUAHSUEAHEUAH
- [x] 4.  historico expandido, mostrando detalhes da aposta ainda na linha do perfil (o nome do grupo, a data, numero de participantes e valor da aposta, e vencedor.)
- [x] 5.  remocao do nome publico
- [x] 6.  mudar  a cor para a cor do facebook
- [x] 7.  adicionar uma maldita roleta HEUASEHAU pode ser so flash no nome dos participantes

**Comment by felipevfa** [comment]
Parte do app foi facebookado. Faltam ajustes.

Histórico expandido adicionado na página do usuário (somente em desktop).

**Comment by felipevfa** [comment]
Facebookado.

Com o fundo branco, o help_text (vermelho) não se confunde mais com fundo.

Histórico expandido agora aparece em dispositivos médios (tablets).

Precisa centralizar o captcha.
